version: "3.5"
services:
 weby:
  deploy:
   restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 60s
   resources:
    limits:
     cpus: "0.50"
     memory: 128M
    reservations:
     cpus: "0.25"
     memory: 32M
   mode: replicated
   replicas: 3
  image: bloby01/web:1
  volumes:
   - web:/var/www/html/
  ports:
   - "80:80"
volumes:
 web:
